<?php
namespace ResourceCatalog\Model;

interface IResourceCatalog extends IResourceCatalogTypeName, IResourceCatalogTypeIdentify, IResourceCatalogTypeEnName, IResourceCatalogTypeDoublePublicity, IResourceCatalogTypeRedBlackList, IResourceCatalogIsConfirm
{
    const TYPE = array(
        'NULL' => 0,
        'MZSHTTHMBFQYDW' => 1,
        'QYJBXX' => 2,
        'QYYCMLXX' => 3,
        'SXQYHMD' => 4,
        'DYZGXX' => 5,
        'QYGDZCTZXMHZHBA' => 6,
        'ZFCGDLJGXX' => 7,
        'QYGSZXXX' => 8,
        'AJNSRXX' => 9,
        'QYDSXZCFXX' => 10,
        'YSCRJZJJJZGRDXX' => 11,
        'SFJDJGCYRYZGXX' => 12,
        'QXTCHJBHJDXX' => 13,
        'PXSTYXHDJXX' => 14,
        'HSZYZGZXX' => 15,
        'JGJCDXZJL' => 16,
        'JXSZLJDW' => 17,
        'ZLJCQYXX' => 18,
        'SLGCZBXX' => 19,
        'ESCJDPGJGHZZS' => 20,
        'PGJGXX' => 21,
        'DTJXJGRXX' => 22,
        'YXZZDWJBGXX' => 23,
        'SLYSXKZXX' => 24,
        'ZYJNZSXX' => 25,
        'QYRYXX' => 26,
        'SHZZNJXX' => 27,
        'YLBXXX' => 28,
        'TJDCDXML' => 29,
        'JDCWFXX' => 30,
        'GTGSHXX' => 31,
        'CMQYSBXX' => 32,
        'YPLSQYXX' => 33,
        'YZTQSBXXHMD' => 34,
        'JGRYXX' => 35,
        'SPYPTSJBJLGR' => 36,
        'SPYPTSJBJLDW' => 37,
        'JXMPCPXX' => 38,
        'JSZGXX' => 39,
        'SJYXXS' => 40,
        'SYBXXX' => 41,
        'SJJXMXX' => 42,
        'JYJGXINXI' => 43,
        'GRRYXXJYJ' => 44,
        'GRRYXXJTJ' => 45,
        'GRRYXXGDJ' => 46,
        'GRRYXXMZJ' => 47,
        'SBQYXX' => 48,
        'SFJDJGDJXX' => 49,
        'GZJGJBXX' => 50,
        'GZYXX' => 51,
        'JCFLFWSXX' => 52,
        'JCFLFWGZZJBXX' => 53,
        'LSSWSXX' => 54,
        'LSZYZGZXX' => 55,
        'GZRYXX' => 56,
        'YSZYZCHBGZC' => 57,
        'YSZYZGZXX' => 58,
        'WSHJHSYWYHJCXX' => 59,
        'YLHJSFWJGXX' => 60,
        'JBYFKZJGXX' => 61,
        'FYCRYJLXX' => 62,
        'WSZYJSZGKSWJXX' => 63,
        'QSWCXXXJDWBZ' => 64,
        'YZTQNMGGZHMD' => 65,
        'JGRYXXSWGXJ' => 66,
        'JGRYXXSJYJ' => 67,
        'JGRYXXSSFJ' => 68,
        'MBFQYML' => 69,
        'SHTTDJXX' => 70,
        'QYZXXX' => 71,
        'QYDXXX' => 72,
        'CCJCJGXX' => 73,
        'TZXMBLJGGSXX' => 74,
        'TZXMMCDMPPXX' => 75,
        'SFJDRXX' => 76,
        'SFJDJGXX' => 77,
        'LSZYXX' => 78,
        'LSNDPJXX' => 79,
        'LSSWSNDPJXX' => 80,
        'SAJLVJQ' => 81,
        'BWGXX' => 82,
        'WWSDXX' => 83,
        'WWSDGMXSJLSX' => 84,
        'QYSWJBDJXX' => 85,
        'NSXYDJPDXX' => 86,
        'QYQSGGXX' => 87,
        'FZCNSRXX'=> 88,
        'LXSDJXX' => 89,
        'GRYCJJBAXX' => 90,
        'XZJLXXZRR' => 91,
        'XZJLXXFRHQTZZ' => 92,
        'XBXZCF' => 93,
        'XBXZXK' => 94,
    );

    const USERGROUP_TYPE_RELATIONSHIP = array(
        IUserGroup::ID['NULL'] => array(
            self::TYPE['NULL'],
            self::TYPE['XBXZCF'],
            self::TYPE['XBXZXK']
        ),
        IUserGroup::ID['FGW'] => array(
            self::TYPE['JGJCDXZJL'], 
            self::TYPE['SJJXMXX'], 
            self::TYPE['TZXMBLJGGSXX'], 
            self::TYPE['TZXMMCDMPPXX'], 
            self::TYPE['QYGDZCTZXMHZHBA'],
        ),
        IUserGroup::ID['JYJ'] => array(
            self::TYPE['JSZGXX'],
            self::TYPE['SJYXXS'],
            self::TYPE['JYJGXINXI'],
            self::TYPE['GRRYXXJYJ'],
            self::TYPE['JGRYXXSJYJ'],
        ),
        IUserGroup::ID['KJJ'] => array(
            self::TYPE['JXSZLJDW'],
        ),
        IUserGroup::ID['JXW'] => array(),
        IUserGroup::ID['MZSWWYH'] => array(),
        IUserGroup::ID['GAJ'] => array(
            self::TYPE['YSCRJZJJJZGRDXX'],
            self::TYPE['JDCWFXX'],
        ),
        IUserGroup::ID['MZJ'] => array(
            self::TYPE['MZSHTTHMBFQYDW'], 
            self::TYPE['SHZZNJXX'], 
            self::TYPE['GRRYXXMZJ'], 
            self::TYPE['MBFQYML'], 
            self::TYPE['SHTTDJXX'],
        ),
        IUserGroup::ID['SFJ'] => array(
            self::TYPE['SFJDJGCYRYZGXX'],
            self::TYPE['SFJDJGDJXX'],
            self::TYPE['GZJGJBXX'],
            self::TYPE['GZYXX'],
            self::TYPE['JCFLFWSXX'],
            self::TYPE['JCFLFWGZZJBXX'],
            self::TYPE['LSSWSXX'],
            self::TYPE['LSZYZGZXX'],
            self::TYPE['JGRYXXSSFJ'],
            self::TYPE['SFJDRXX'],
            self::TYPE['SFJDJGXX'],
            self::TYPE['LSZYXX'],
            self::TYPE['LSNDPJXX'],
            self::TYPE['LSSWSNDPJXX'],
        ),
        IUserGroup::ID['CZJ'] => array(
            self::TYPE['ZFCGDLJGXX'],
        ),
        IUserGroup::ID['RSJ'] => array(
            self::TYPE['ZYJNZSXX'], 
            self::TYPE['YLBXXX'], 
            self::TYPE['YZTQSBXXHMD'], 
            self::TYPE['SYBXXX'], 
            self::TYPE['SBQYXX'],
            self::TYPE['GZRYXX'],
            self::TYPE['YZTQNMGGZHMD'],
        ),
        IUserGroup::ID['GZW'] => array(
            self::TYPE['QYRYXX'],
        ),
        IUserGroup::ID['GHJ'] => array(
            self::TYPE['PGJGXX'],
        ),
        IUserGroup::ID['ZJJ'] => array(
            self::TYPE['ZLJCQYXX'],
            self::TYPE['JXMPCPXX'],
            self::TYPE['CCJCJGXX'],
        ),
        IUserGroup::ID['HBJ'] => array(),
        IUserGroup::ID['JTJ'] => array(
            self::TYPE['SLYSXKZXX'],
            self::TYPE['GRRYXXJTJ'],
        ),
        IUserGroup::ID['SWJ'] => array(
            self::TYPE['SLGCZBXX'],
        ),
        IUserGroup::ID['NMJ'] => array(),
        IUserGroup::ID['LCJ'] => array(),
        IUserGroup::ID['SHANGWJ'] => array(
            self::TYPE['ESCJDPGJGHZZS'],
        ),
        IUserGroup::ID['WGJ'] => array(
            self::TYPE['YXZZDWJBGXX'], 
            self::TYPE['GRRYXXGDJ'], 
            self::TYPE['JGRYXXSWGXJ'], 
            self::TYPE['GRYCJJBAXX'], 
            self::TYPE['XZJLXXZRR'],
            self::TYPE['XZJLXXFRHQTZZ'],
        ),
        IUserGroup::ID['WJW'] => array(
            self::TYPE['HSZYZGZXX'], 
            self::TYPE['YSZYZCHBGZC'], 
            self::TYPE['YSZYZGZXX'], 
            self::TYPE['WSHJHSYWYHJCXX'], 
            self::TYPE['YLHJSFWJGXX'],
            self::TYPE['JBYFKZJGXX'],
            self::TYPE['FYCRYJLXX'], 
            self::TYPE['WSZYJSZGKSWJXX'],
            self::TYPE['QSWCXXXJDWBZ'],
        ),
        IUserGroup::ID['SJJ'] => array(),
        IUserGroup::ID['TYJ'] => array(
            self::TYPE['PXSTYXHDJXX'],
        ),
        IUserGroup::ID['SYJ'] => array(
            self::TYPE['YPLSQYXX'],
            self::TYPE['SPYPTSJBJLGR'],
            self::TYPE['SPYPTSJBJLDW'],
        ),
        IUserGroup::ID['GSJ'] => array(
            self::TYPE['QYJBXX'], 
            self::TYPE['QYYCMLXX'], 
            self::TYPE['SXQYHMD'], 
            self::TYPE['GTGSHXX'], 
            self::TYPE['CMQYSBXX'],
            self::TYPE['QYZXXX'],
            self::TYPE['QYDXXX'], 
        ),
        IUserGroup::ID['ZJJ'] => array(
            self::TYPE['JGRYXX'],
        ),
        IUserGroup::ID['AJJ'] => array(),
        IUserGroup::ID['TJJ'] => array(
            self::TYPE['DTJXJGRXX'],
            self::TYPE['TJDCDXML'],
        ),
        IUserGroup::ID['LFW'] => array(
            self::TYPE['DYZGXX'],
            self::TYPE['SAJLVJQ'],
            self::TYPE['BWGXX'],
            self::TYPE['WWSDXX'],
            self::TYPE['WWSDGMXSJLSX'],
            self::TYPE['LXSDJXX'],
        ),
        IUserGroup::ID['LSJ'] => array(),
        IUserGroup::ID['JRB'] => array(),
        IUserGroup::ID['RF'] => array(),
        IUserGroup::ID['FPB'] => array(),
        IUserGroup::ID['SHUIWJ'] => array(
            self::TYPE['QYGSZXXX'],
            self::TYPE['AJNSRXX'],
            self::TYPE['QYDSXZCFXX'],
            self::TYPE['QYSWJBDJXX'],
            self::TYPE['NSXYDJPDXX'],
            self::TYPE['QYQSGGXX'],
            self::TYPE['FZCNSRXX'],
        ),
        IUserGroup::ID['CRJJYJYJ'] => array(),
        IUserGroup::ID['QXJ'] => array(
            self::TYPE['QXTCHJBHJDXX'],
        ),
        IUserGroup::ID['HG'] => array(),
        IUserGroup::ID['YZJ'] => array(),
        IUserGroup::ID['YWJ'] => array(),
        IUserGroup::ID['TLSYCJ'] => array(),
    );

    const STATUS_NORMAL = 0;

    const STATUS_DELETE = -2;
}