<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['FGW'] => 'FGW',
        IUserGroup::ID['JYJ'] => 'JYJ',
        IUserGroup::ID['KJJ'] => 'KJJ',
        IUserGroup::ID['JXW'] => 'JXW',
        IUserGroup::ID['MZSWWYH'] => 'MZSWWYH',
        IUserGroup::ID['GAJ'] => 'GAJ',
        IUserGroup::ID['MZJ'] => 'MZJ',
        IUserGroup::ID['SFJ'] => 'SFJ',
        IUserGroup::ID['CZJ'] => 'CZJ',
        IUserGroup::ID['RSJ'] => 'RSJ',
        IUserGroup::ID['GZW'] => 'GZW',
        IUserGroup::ID['GHJ'] => 'GHJ',
        IUserGroup::ID['ZJJ'] => 'ZJJ',
        IUserGroup::ID['HBJ'] => 'HBJ',
        IUserGroup::ID['JTJ'] => 'JTJ',
        IUserGroup::ID['SWJ'] => 'SWJ',
        IUserGroup::ID['NMJ'] => 'NMJ',
        IUserGroup::ID['LCJ'] => 'LCJ',
        IUserGroup::ID['SHANGWJ'] => 'SHANGWJ',
        IUserGroup::ID['WGJ'] => 'WGJ',
        IUserGroup::ID['WJW'] => 'WJW',
        IUserGroup::ID['SJJ'] => 'SJJ',
        IUserGroup::ID['TYJ'] => 'TYJ',
        IUserGroup::ID['SYJ'] => 'SYJ',
        IUserGroup::ID['GSJ'] => 'GSJ',
        IUserGroup::ID['ZJJ'] => 'ZJJ',
        IUserGroup::ID['AJJ'] => 'AJJ',
        IUserGroup::ID['TJJ'] => 'TJJ',
        IUserGroup::ID['LFW'] => 'LFW',
        IUserGroup::ID['LSJ'] => 'LSJ',
        IUserGroup::ID['JRB'] => 'JRB',
        IUserGroup::ID['RF'] => 'RF',
        IUserGroup::ID['FPB'] => 'FPB',
        IUserGroup::ID['SHUIWJ'] => 'SHUIWJ',
        IUserGroup::ID['CRJJYJYJ'] => 'CRJJYJYJ',
        IUserGroup::ID['QXJ'] => 'QXJ',
        IUserGroup::ID['HG'] => 'HG',
        IUserGroup::ID['YZJ'] => 'YZJ',
        IUserGroup::ID['YWJ'] => 'YWJ',
        IUserGroup::ID['TLSYCJ'] => 'TLSYCJ',
    );
}
